linters:
  enable-all: true
  disable:
    - godot
    - depguard
    - ireturn
    - godox
    - tagliatelle
    - exhaustruct # Unable to configure excludes
    - exhaustivestruct # Unable to configure excludes


severity:
  default-severity: error
  rules:
    - linters:
      - musttag
      - nonamedreturns
      severity: warning
    - linters:
      - nlreturn
      severity: info


issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - goconst
        - varnamelen

linters-settings:
  varnamelen:
    ignore-names:
      - id
    ignore-decls:
      - is bool
      - ok bool
  gomnd:
    ignored-functions:
      - '\.Some$'
      - '\.UnwrapOr$'
