linters:
  enable-all: true
  disable:
    - tagliatelle
    - godot
    - depguard
    - exhaustivestruct
    - exhaustruct
    - ireturn
    - godox
severity:
  default-severity: error
  rules:
    - linters:
      - musttag
      - nonamedreturns
      severity: warning
    - linters:
      - nlreturn
      severity: info
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - goconst
        - varnamelen
