linters:
  enable-all: true
  disable:
    - godot
    - depguard
    - ireturn
    - godox
    - tagliatelle
    - exhaustivestruct # Replaced by exhaustruct
    - exhaustruct


severity:
  default-severity: error
  rules:
    - linters:
      - musttag
      - nonamedreturns
      severity: warning
    - linters:
      - nlreturn
      severity: info


issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - goconst
        - varnamelen

linters-settings:
  exhaustruct:
    include: []
    exclude:
      - "url.URL"
      - "http.Client"
  varnamelen:
    ignore-names:
      - id
    ignore-decls:
      - is bool
      - ok bool
  gomnd:
    ignored-functions:
      - '\.Some$'
      - '\.UnwrapOr$'
  nolintlint:
    require-explanation: true
    allow-no-explanation:
    require-specific: true
  govet:
    settings:
      printf:
        funcs:
          - github.com/m-kuzmin/daily-reporter/internal/util/logging.Tracef
          - github.com/m-kuzmin/daily-reporter/internal/util/logging.Debugf
          - github.com/m-kuzmin/daily-reporter/internal/util/logging.Infof
          - github.com/m-kuzmin/daily-reporter/internal/util/logging.Errorf
          - github.com/m-kuzmin/daily-reporter/internal/util/logging.Fatalf
  forbidigo:
    forbid:
      - ^(fmt\.print(|f|ln)|print|println)$
      - ^log\..*$
    exclude-godoc-examples: true
    analyze-types: true
